### PR TITLE
docs: move license from README.md to LICENSE.md

### PR DESCRIPTION
**Pull request by bufferoverflow**
A widely adopted best practice is having a LICENSE.md file, so I've moved the license out from README.md to a dedicated file.

### CODE REVIEW

**Comment by md5** [comment]
How about adding a link to the license file in `README.md`? Other that that, this looks good to me :+1:

**Comment by bufferoverflow** [comment]
Here is the updated commit, what about the Authors at the end of README.md and within omniauth-saml.gemspec ? Shall we combine this somehow? Any idea?

Shall omniauth-saml.gemspec shall contain the same people as on https://rubygems.org/gems/omniauth-saml ?

**Comment by md5** [comment]
I'm not sure who should be listed as authors in the Gemspec and on Rubygems.org. I don't think that needs to be resolved in this PR. Perhaps it would make sense to discuss that at #67 instead.

**Comment by bufferoverflow** [comment]
@md5 yes, you are right that's a separate topic. So I suggest you merge this.

**Pull request merged**
