### PR TITLE
Update ruby-saml dependency 1.9.0 version

### PR DESCRIPTION
**Pull request by SokratisVidros**
Changes for v1.8.x and 1.9.x can be found at https://github.com/onelogin/ruby-saml/blob/master/changelog.md

Thanks,
Sokratis

### CODE REVIEW

**Comment by md5** [comment]
@SokratisVidros What's the need to upgrade this dependency? I don't see any security fixes in the changelog for 1.8 and 1.9, so I'm not sure we have a reason to bump this. Users can already install the latest version of `ruby-saml` if they wish.

**Comment by SokratisVidros** [comment]
We use omniauth-saml in our app however we need to be able to get the latest change from ruby-saml 1.9 regarding the "allowed_clock_drift" setting in non number format. It would be really helpful to avoid forking this repo in the meantime.

**Comment by md5** [comment]
@SokratisVidros There is no need to fork. 1.9 is compatible with the `~> 1.7` version specification.

**Comment by supernova32** [comment]
I agree with @md5 here. Since there are no vulnerability fixes between the versions, I see little gain by increasing the required minimum version of `ruby-saml`. As Mike mentioned, you can easily add `ruby-saml` 1.9 to your Gemfile and the configuration options will work without having to fork.

**Pull request merged**
