### PR TITLE
feat: create initial CONTRIBUTING.md

### LINKED ISSUE #77: add a CONTRIBUTING.md file
As mentioned within #73 we need a CONTRIBUTING.md file, this has a nice side effect: https://github.com/blog/1184-contributing-guidelines

### PR DESCRIPTION
**Pull request by bufferoverflow**
This closes #77

### CODE REVIEW

**Comment by md5** [comment]
I'm not a fan of the `type:` annotation on commits. I think it's sets a higher bar for outside contributions than is desirable.

**Comment by bufferoverflow** [comment]
The changelog-generators(e.g. [nodejs variant](https://github.com/ajoslin/conventional-changelog)) are usually configurable, e.g. by default you only have feat and fix to be included within CHANGELOG.md this reduces info on style changes, etc.

Outside contributers are usually familiar with this quickly, they have a look at the commit log and see what type to use and if not we can stash and amend.

**Comment by supernova32** [comment]
If no one has any objections, I'd like to merge this today.

**Comment by md5** [comment]
:+1:

**Pull request merged**
