### PR TITLE
feat: new release 2.1.0

### PR DESCRIPTION
**Pull request by bufferoverflow**

### CODE REVIEW

**Comment by bufferoverflow** [comment]
@suprnova32 I will tag and publish a new gem as soon as this is merged

**Review by suprnova32 — APPROVED** [review]

**Comment by rajiv** [comment]
FYI, the `ruby-saml` https://github.com/SAML-Toolkits/ruby-saml/security/advisories/GHSA-jw9c-mfg7-9rx2 suggested that `omniauth-saml` **2.2.0**, not 2.1.1, would be the patched version.

**Comment by rajiv** [comment]
Perhaps @pitbulk could update https://github.com/SAML-Toolkits/ruby-saml/security/advisories/GHSA-jw9c-mfg7-9rx2 to indicate that 2.1.1 is patched?

**Comment by bufferoverflow** [comment]
thanks @rajiv I've not seen that. I will just craft a new release 2.2.0 so we are done.

**Comment by jlocke2** [comment]
@bufferoverflow @pitbulk - Can https://github.com/SAML-Toolkits/ruby-saml/security/advisories/GHSA-jw9c-mfg7-9rx2 and https://github.com/omniauth/omniauth-saml/security/advisories/GHSA-cvp8-5r8g-fhvq be updated to indicate that `1.10.5` is also patched?

**Comment by bufferoverflow** [comment]
I updated https://github.com/omniauth/omniauth-saml/security/advisories/GHSA-cvp8-5r8g-fhvq

**Pull request merged**
